# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ee4bf9b7d81d7e082959e653b2faacf8bb80862a486734dcb902f2b978823693c3b28fb15111accf9c49b71fbf96c2bd269a8cc7c85bd490bcf16548abdacd

test:
  secret_key_base: 0349a57124c44ba8ba96cbb5ed8cc4545bfc7fb891759d3afeff33eb3047c3b49309262bbc9fc8dc801e79e481b5d2212a6e8cabb53eac84b13cfd48dab41848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
